
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-3
pull_requests: [{"author":{"id":"U_kgDOBXuwTQ","is_bot":false,"login":"hugolin0","name":""},"headRefName":"Hugo-MenuItemReviewTableComponent","number":66,"title":"Add MenuItemReview Table Component and Tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/66"},{"author":{"id":"U_kgDOBXuwTQ","is_bot":false,"login":"hugolin0","name":""},"headRefName":"Hugo-MenuItemReviewForm","number":65,"title":"Add MenuItemReview Form Component","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/65"},{"author":{"id":"U_kgDOBXuwTQ","is_bot":false,"login":"hugolin0","name":""},"headRefName":"Hugo-MenuItemReviewFrontend","number":64,"title":"Add MenuItemReview Fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/64"},{"author":{"id":"U_kgDOBXuwTQ","is_bot":false,"login":"hugolin0","name":""},"headRefName":"Hugo-MenuItemReviewBackend","number":63,"title":"Add MenuItemReview Backend Files","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/63"},{"author":{"id":"U_kgDOBdHRmA","is_bot":false,"login":"srambhatla30","name":""},"headRefName":"Sid-HelpRequest-fixtures","number":62,"title":"Merge fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/62"},{"author":{"id":"U_kgDOBdHRmA","is_bot":false,"login":"srambhatla30","name":""},"headRefName":"Sid-HelpRequest-backend","number":61,"title":"Adding backend files for HelpRequest","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/61"}]
