
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQwNDAzOTY0","is_bot":false,"login":"aardvarkzone","name":"Advait Arumugam"},"headRefName":"Articles-CreatePage","number":116,"title":"Articles create page + test + stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/116"},{"author":{"id":"MDQ6VXNlcjQwNDAzOTY0","is_bot":false,"login":"aardvarkzone","name":"Advait Arumugam"},"headRefName":"aardvarkzone-Read-me","number":115,"title":"Update README.md","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/115"},{"author":{"id":"U_kgDOBdHRmA","is_bot":false,"login":"srambhatla30","name":""},"headRefName":"Sid-HelpRequest-form","number":86,"title":"Sid help request form","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/86"}]
