
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-3
pull_requests: [{"author":{"id":"U_kgDOBX3XaQ","is_bot":false,"login":"bonniehuynh","name":""},"headRefName":"Bonnie-RecRequest-EditPage","number":122,"title":"bh - fixed boolean showing up in form","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/122"},{"author":{"id":"MDQ6VXNlcjY2ODkyOTQw","is_bot":false,"login":"konarkv","name":""},"headRefName":"Konark-MenuItems-Table","number":121,"title":"Konark menu items table","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/121"},{"author":{"id":"MDQ6VXNlcjY2ODkyOTQw","is_bot":false,"login":"konarkv","name":""},"headRefName":"Konark-MenuItems-FormComponent","number":120,"title":"Konark menu items form component","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/120"}]
