
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-3
pull_requests: [{"author":{"id":"U_kgDOBdHRmA","is_bot":false,"login":"srambhatla30","name":""},"headRefName":"Sid-HelpRequest","number":138,"title":"Sid help request","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/138"},{"author":{"id":"U_kgDOBX3XaQ","is_bot":false,"login":"bonniehuynh","name":""},"headRefName":"Bonnie-RecRequest-EditPage","number":136,"title":"Bonnie rec request edit page","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/136"},{"author":{"id":"MDQ6VXNlcjY2ODkyOTQw","is_bot":false,"login":"konarkv","name":""},"headRefName":"Konark-MenuItems-Placeholders","number":135,"title":"fixed placeholders tests hopefully","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-3/pull/135"}]
